### ISSUE TITLE
MSAA?

### ISSUE THREAD

**Issue by VinnyVicious** [pezcode/Cluster#12]
Results are very noisy without any filtering. Is it possible to add MSAA to this rendering technique?

![image](https://user-images.githubusercontent.com/184960/178866927-8e966e86-47b0-49de-a5d6-4e02f61585c5.png)

**Comment by pezcode** [comment]
It looks like your textures don't have mipmaps. MSAA only helps with anti-aliasing along triangle edges.

But yes, you can enable MSAA by creating the intermediate framebuffer attachments with MSAA. Try adding `BGFX_TEXTURE_RT_MSAA_X4` to the `createTexture2D()` calls here: https://github.com/pezcode/Cluster/blob/a25ff3270e8aa1818840dd00d128010fab6dc62b/src/Renderer/Renderer.cpp#L221

(*Note: This won't work correctly for the deferred renderer, you'd need some post-process anti-aliasing there*)

**Comment by VinnyVicious** [comment]
Oh, that does the trick:

![image](https://user-images.githubusercontent.com/184960/179259151-1397a1c3-f59f-434f-89da-cf192a8a92d7.png)

Thank you, you're a genius. :)

**Comment by VinnyVicious** [comment]
With mips:
![image](https://user-images.githubusercontent.com/184960/179279288-9116f84e-4b43-42f5-a9d9-9c89477990ff.png)
