### ISSUE TITLE
SSAO or GTAO

### ISSUE THREAD

**Issue by VinnyVicious** [pezcode/Cluster#13]
Ambient occlusion addresses medium to long range occlusion of ambient light (which is light that has undergone many bounces and is in some sense 'omnidirectional'). It would be cool to have a toggle for SSAO or GTAO on the clustered renderer.

**Comment by pezcode** [comment]
Would be cool, but maybe a little out of scope for this repo :eyes: I want to keep this somewhat centered around comparing shading techniques. Adding other unrelated features makes it more confusing to learn from the code and adapt it.

If you're looking for an SSAO implementation, there's one in the bgfx examples: https://bkaradzic.github.io/bgfx/examples.html#assao
