### ISSUE TITLE
Sponza and metallic factor

### ISSUE THREAD

**Issue by clibequilibrium** [pezcode/Cluster#15]
Hello @pezcode 

I hope you are doing well. I am reaching out about metallic factor on Sponza scene where cloth has gold string and was wondering why it differs from default GLTF [model viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/)?

![image](https://user-images.githubusercontent.com/105135724/199791224-6d70605c-942c-4976-903f-77790cb0ec2a.png)

What I see is 

` // metals have no diffuse reflection so the albedo value stores F0 (reflectance at normal incidence) instead
    // dielectrics are assumed to have F0 = 0.04 which equals an IOR of 1.5
    mat.diffuseColor = mix(mat.albedo.rgb * (vec3_splat(1.0) - dielectricSpecular), black, mat.metallic);`

in pbr.sh, changing mat.metallic to 0.5 produces more or less metallic look of the cloth

![image](https://user-images.githubusercontent.com/105135724/199791819-2477faa9-53c4-4f78-985e-82f852e85697.png)

Removing mix with `mat.diffuseColor = mat.albedo.rgb * (vec3_splat(1.0) - dielectricSpecular);` also produces non black result.

![image](https://user-images.githubusercontent.com/105135724/199793065-5c49d160-c91a-4c69-8a92-366d692c91fc.png)

Do you think it is expect that mix would fully use black color when mat.metallic is 1? It makes mat.diffuseColor absolutely black

Thanks !

**Comment by pezcode** [comment]
The lack of diffuse (ie. subsurface) reflection is one of the defining characteristics of a metal. Its entire BRDF is just specular reflection. When you only have point lights in your scene, this will result in black everywhere except where light is reflected directly into the camera.

Compare with the glTF Sample Viewer when turning off Image Based lighting:

![firefox_2022-11-03_18-47-08](https://user-images.githubusercontent.com/907940/199798678-3f0c2e1f-af86-49be-b598-4e43a9883a71.png)

The math should more or less match the [glTF sample implementation](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#metal-brdf-and-dielectric-brdf). The code here modulates the diffuse color by the IOR, I'm not sure if that's actually correct (the glTF sample doesn't do that), but the difference should be minimal.

**Comment by clibequilibrium** [comment]
> The lack of diffuse (ie. subsurface) reflection is one of the defining characteristics of a metal. Its entire BRDF is just specular reflection. When you only have point lights in your scene, this will result in black everywhere except where light is reflected directly into the camera.
> 
> Compare with the glTF Sample Viewer when turning off Image Based lighting:
> 
> ![firefox_2022-11-03_18-47-08](https://user-images.githubusercontent.com/907940/199798678-3f0c2e1f-af86-49be-b598-4e43a9883a71.png)
> 
> The math should more or less match the [glTF sample implementation](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#metal-brdf-and-dielectric-brdf). The code here modulates the diffuse color by the IOR, I'm not sure if that's actually correct (the glTF sample doesn't do that), but the difference should be minimal.

Thank you for your quick reply. Indeed that would make sense when there are only point lights however same occurs on sky light branch under different angles. I think it would only be lit if the light is directed from bottom to top of the map ? 

![image](https://user-images.githubusercontent.com/105135724/199801979-117f3c3e-d000-4500-afb7-bd36584a88cf.png)

**Comment by pezcode** [comment]
Yeah, directional lights suffer from the same problem. In real life, you have light coming in from all directions because of global illumination. The glTF sample viewer approximates that with Image Based Lighting. That way every incoming camera angle ends up reflecting into the skybox (I'm being very loose here with terminology).

**Comment by clibequilibrium** [comment]
> Yeah, directional lights suffer from the same problem. In real life, you have light coming in from all directions because of global illumination. The glTF sample viewer approximates that with Image Based Lighting. That way every incoming camera angle ends up reflecting into the skybox (I'm being very loose here with terminology).

Lovely thank you so much for explaining and reasoning. So to solve it I can try to implement IBL or add GI which would be outside of this repository scope . Take care @pezcode  !
